### ISSUE TITLE
[BUG] Incorrect Installation Instructions

### ISSUE THREAD

**Issue by UnoYakshi** [manuelescobar-dev/LLM-Tools#1]
https://github.com/manuelescobar-dev/LLM-Tools?tab=readme-ov-file#installation doesn't really work on step `poetry install` as `pyproject.toml` is missing.
![image](https://github.com/user-attachments/assets/6108467e-718c-485b-a618-d6451aab3194)

**Comment by manuelescobar-dev** [comment]
This issue is resolved by PR #2 .
